// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ppmttriazvcymnweiyry.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBwbXR0cmlhenZjeW1ud2VpeXJ5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4ODc1MzAsImV4cCI6MjA2MDQ2MzUzMH0.0zaAyLqSw75C4d5Odd2rkj1qvqQ5mBZIuaAhHHOex9c";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);